### PR TITLE
no_std integration

### PR DESCRIPTION
**Pull request by drewstone**

### CODE REVIEW

**Comment by drewstone** [comment]
https://github.com/matter-labs/eip1962/issues/12

**Comment by shamatar** [comment]
This does not look to be "no_std" compatible, but instead liballoc or parity substrate compatible. I should have some replacement for vectors with fixed capacity and constant constructors, that should be enough for all purposes.

**Comment by drewstone** [comment]
Ok, I was able to compile this sort of thing in the repo I need, which requires no_std. Are the vec implementations really that different between alloc and arrayvec?

**Comment by shamatar** [comment]
What is your target platform? In pure no_std there are no e.g. Read/Write traits, Vecs (that are used in pairings) and strings, so it actually requires quite a lot of work to make it compile

**Comment by drewstone** [comment]
We’re compiling down into WASM.

**Comment by drewstone** [comment]
I'lll keep testing, perhaps I did not do entirely what I needed as well.

**Comment by drewstone** [comment]
Welp, I can never grok this `no_std` stuff, 5 hours of debugging today and I'm 1000 errors deep... :(

**Comment by shamatar** [comment]
I've looked at what has to be done myself, and it needs to:
- change few traits to instead of returning e.g `Vec<i16>` to write into mutable slice and return number of elements
- get rid of `Read/Write`
- change errors from containing `String` to either `'static str` or just use enums and find some no_std formatter
- internally instead of vectors in some places use something like `arrayvec`

I've already updated fixed width integer implementation in my branch to allow initialization from radix-10 and radix-16 literals, so one can remove dependency on bigint completely unless used for testing

**Pull request closed without merging**
